var spec = {
	"openapi":"3.0.0",
	"info":{
	"description":"API for managing print mappings",
	"version":"1.0.0",
	"title":"qBroker",
	"termsOfService":"http://swagger.io/terms/",
	"contact":{
		"email":"lyas.spiehler@sapphirehealth.org"
	},
	"license":{
			"name":"Apache 2.0",
			"url":"http://www.apache.org/licenses/LICENSE-2.0.html"
		}
	},
	/*"tags":[
		{
			"name":"qBroker",
			"description":"Manage print mappings",
			"externalDocs":{
				"description":"Find out more",
				"url":"https://github.com/lspiehler/qBroker.git"
			}
		}
	],*/
	"paths":{
		"/mappings/{computername}/{username}":{
			"get":{
				"tags":[
					"queue management"
				],
				"summary":"Request print mappings",
				"description":"",
				"parameters":[
					{
					"name":"computername",
					"in":"path",
					"description":"The computer name the mappings are being requested for",
					"required":true,
					"schema":{
						"type":"string",
						"default":"DESKTOP-HS0AL31"
					}
					},
					{
					"name":"username",
					"in":"path",
					"description":"The user name the mappings are being requested for",
					"required":true,
					"schema":{
						"type":"string",
						"default":"LYAS.SPIEHLER"
					}
					}
				],
				"responses":{
					"200":{
					"description":"OK",
					"content":{
						"application/json":{
							"schema":{
								"type":"string"
							}
						},
						"application/xml":{
							"schema":{
								"type":"string"
							}
						}
					}
					}
				}
			}
		},
		"/activeservers":{
			"get":{
				"tags":[
					"queue management"
				],
				"summary":"Request active servers",
				"description":"",
				"responses":{
					"200":{
					"description":"OK",
					"content":{
						"application/json":{
							"schema":{
								"type":"string"
							}
						},
						"application/xml":{
							"schema":{
								"type":"string"
							}
						}
					}
					}
				}
			}
		},
		"/status/dns":{
			"get":{
				"tags":[
					"status"
				],
				"summary":"Test DNS resolution of qBroker SRV records",
				"description":"",
				"responses":{
					"200":{
					"description":"OK",
					"content":{
						"application/json":{
							"schema":{
								"type":"string"
							}
						},
						"application/xml":{
							"schema":{
								"type":"string"
							}
						}
					}
					}
				}
			}
		},
		"/status/mount":{
			"get":{
				"tags":[
					"status"
				],
				"summary":"Get status of mapping file mount",
				"description":"",
				"responses":{
					"200":{
					"description":"OK",
					"content":{
						"application/json":{
							"schema":{
								"type":"string"
							}
						},
						"application/xml":{
							"schema":{
								"type":"string"
							}
						}
					}
					}
				}
			}
		},
		"/status/hostname":{
			"get":{
				"tags":[
					"status"
				],
				"summary":"Return hostname of responding qBroker server",
				"description":"",
				"responses":{
					"200":{
					"description":"OK",
					"content":{
						"application/json":{
							"schema":{
								"type":"string"
							}
						},
						"application/xml":{
							"schema":{
								"type":"string"
							}
						}
					}
					}
				}
			}
		}
	},
	"externalDocs":{
	"description":"Find out more about Swagger",
	"url":"http://swagger.io"
	},
	"servers":[
		{
			"url":"/api"
		}
	]
}